# Generated by Django 5.0.9 on 2024-11-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comrade_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="latitude",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="longitude",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
