# Generated by Django 5.0.3 on 2024-11-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comrade_core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="title",
            new_name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.ManyToManyField(blank=True, to="comrade_core.skill"),
        ),
    ]
