# Generated by Django 5.0.3 on 2024-11-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comrade_core", "0002_rename_title_skill_name_user_skills"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="title",
            new_name="name",
        ),
    ]
