# Generated by Django 5.0.3 on 2024-03-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comrade_core", "0002_rename_description_text_task_description_task_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="lat",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="lon",
            field=models.FloatField(null=True),
        ),
    ]
