# Generated by Django 5.0.3 on 2024-11-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comrade_core", "0003_rename_title_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
