# Generated by Django 5.0.3 on 2024-03-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comrade_core", "0003_task_lat_task_lon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("happines", models.FloatField(default=3)),
                ("time", models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="base_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="criticality",
            field=models.IntegerField(
                choices=[(1, "Low"), (2, "Medium"), (3, "High")], default=1
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="datetime_finish",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="datetime_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="minutes",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="task",
            name="state",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Unavailable"),
                    (1, "Open"),
                    (2, "In Progress"),
                    (3, "Waiting"),
                    (4, "In Review"),
                    (5, "Finished"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="task",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="task",
            name="review",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comrade_core.review",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="skill_read",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comrade_core.skill",
            ),
        ),
    ]
