# Generated by Django 5.0.3 on 2024-03-19 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comrade_core", "0004_review_skill_task_base_value_task_criticality_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="review",
        ),
        migrations.AddField(
            model_name="review",
            name="task",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="comrade_core.task",
            ),
        ),
        migrations.RemoveField(
            model_name="task",
            name="skill_read",
        ),
        migrations.AddField(
            model_name="task",
            name="skill_read",
            field=models.ManyToManyField(to="comrade_core.skill"),
        ),
    ]
