# Generated by Django 5.0.3 on 2024-03-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comrade_core", "0005_remove_task_review_review_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="skill_execute",
            field=models.ManyToManyField(
                related_name="execute", to="comrade_core.skill"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="skill_write",
            field=models.ManyToManyField(related_name="write", to="comrade_core.skill"),
        ),
        migrations.AlterField(
            model_name="task",
            name="skill_read",
            field=models.ManyToManyField(related_name="read", to="comrade_core.skill"),
        ),
    ]
