# Generated by Django 5.0.3 on 2024-03-19 16:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comrade_core", "0006_task_skill_execute_task_skill_write_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="contribution",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="respawn",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="task",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                to="comrade_core.task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="minutes",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MaxValueValidator(480),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
