# Generated by Django 5.0.10 on 2026-03-26 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comrade_core", "0028_user_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="BugReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("url", models.CharField(blank=True, default="", max_length=500)),
                (
                    "screen_size",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("location", models.CharField(blank=True, default="", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bug_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BugReportScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="bug_reports/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "bug_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="comrade_core.bugreport",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
