# Generated by Django 5.0.10 on 2026-03-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comrade_core", "0029_add_bug_report"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LocationConfig",
            new_name="GlobalConfig",
        ),
    ]
