# Generated by Django 5.0.10 on 2026-03-27 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comrade_core", "0030_rename_locationconfig_to_globalconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialpart",
            name="freetext_max_length",
            field=models.PositiveIntegerField(
                default=1000, help_text="Maximum characters for Freetext"
            ),
        ),
        migrations.AddField(
            model_name="tutorialpart",
            name="freetext_min_length",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minimum characters for Freetext (0 = empty accepted)",
            ),
        ),
        migrations.AddField(
            model_name="tutorialprogress",
            name="review_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending Review"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                ],
                default=None,
                help_text="Set to 'pending' when tutorial has an owner requiring review",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tutorialtask",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, tutorial completion requires owner review before skill is awarded",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_tutorials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tutorialpart",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text Page"),
                    ("video", "Video Page"),
                    ("quiz", "Quiz Page"),
                    ("password", "Password Page"),
                    ("file_upload", "File Upload Page"),
                    ("freetext", "Free Text Page"),
                ],
                max_length=20,
            ),
        ),
    ]
