# Generated by Django 5.0.10 on 2026-03-27 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comrade_core", "0032_onboarding_spawn"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingtemplate",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding_templates",
                to="comrade_core.task",
            ),
        ),
        migrations.AlterField(
            model_name="onboardingtemplate",
            name="spawn_radius_meters",
            field=models.PositiveIntegerField(
                default=100, help_text="Max distance from user to spawn"
            ),
        ),
        migrations.AlterField(
            model_name="onboardingtemplate",
            name="tutorial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding_templates",
                to="comrade_core.tutorialtask",
            ),
        ),
        migrations.CreateModel(
            name="UserOnboardingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_onboarding",
                        to="comrade_core.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "task")},
            },
        ),
    ]
