# Generated by Django 5.0.10 on 2026-03-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comrade_core", "0033_onboarding_task_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="useronboardingtask",
            name="completed",
            field=models.BooleanField(
                default=False,
                help_text="Set to True when user finishes this task (persists through respawn)",
            ),
        ),
    ]
