# Generated by Django 5.0.10 on 2026-03-28 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comrade_core", "0035_tutorial_review_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialreview",
            name="decline_reason",
            field=models.TextField(
                blank=True, help_text="Owner's reason when declining", null=True
            ),
        ),
        migrations.CreateModel(
            name="TutorialPartSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_text", models.TextField(blank=True, null=True)),
                (
                    "submitted_file",
                    models.FileField(
                        blank=True, null=True, upload_to="tutorial_submissions/"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="comrade_core.tutorialpart",
                    ),
                ),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="comrade_core.tutorialprogress",
                    ),
                ),
            ],
            options={
                "unique_together": {("progress", "part")},
            },
        ),
    ]
